## 测试appmode

In [1]:
from ipywidgets import interact

In [5]:
@interact(x=5)
def add3(x):
    return x + 3

interactive(children=(IntSlider(value=5, description='x', max=15, min=-5), Output()), _dom_classes=('widget-interact',))

In [4]:
interact(add3, x=5)

interactive(children=(IntSlider(value=5, description='x', max=15, min=-5), Output()), _dom_classes=('widget-interact',))

<function __main__.add3>

In [1]:
len?

In [2]:
this?


Object `this` not found.


In [3]:
add3?

Object `add3` not found.


In [4]:
def aaa():
    """aaa"""
    pass


In [5]:
aaa?

In [6]:
add3?

Object `add3` not found.


In [7]:
aaa??

In [8]:
%magic

In [9]:
Out

{}

In [10]:
In

['',
 "get_ipython().run_line_magic('pinfo', 'len')",
 "get_ipython().run_line_magic('pinfo', 'this')",
 "get_ipython().run_line_magic('pinfo', 'add3')",
 'def aaa():\n    """aaa"""\n    pass',
 "get_ipython().run_line_magic('pinfo', 'aaa')",
 "get_ipython().run_line_magic('pinfo', 'add3')",
 "get_ipython().run_line_magic('pinfo2', 'aaa')",
 "get_ipython().run_line_magic('magic', '')",
 'Out',
 'In']

In [15]:
%debug

> <ipython-input-14-aae42d317509>(1)<module>()
----> 1 a/b

ipdb> b=2
*** The specified object '=2' is not a function or was not found along sys.path.
ipdb> print(b)
0
ipdb> bye
*** NameError: name 'bye' is not defined
ipdb> quit


In [13]:
a=1
b=0

In [14]:
a/b

ZeroDivisionError: division by zero

In [16]:
import numpy

In [17]:
numpy.__version__

'1.13.0'

In [18]:
import numpy as np

In [19]:
np?

In [20]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.full((3, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [22]:
np.arange(0, 100, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
np.linspace(0, 1, 10)

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [2]:
from sympy import *

ModuleNotFoundError: No module named 'sympy'

In [3]:
%matplotlib inline

In [6]:
from sympy import *

In [7]:
I**2

-1

In [8]:
pi

pi

In [11]:
a = Symbol('a')

In [12]:
(pi + a)**2

(a + pi)**2

In [13]:
init_printing()

In [32]:
expand((pi + a)**2)

In [15]:
4/5

In [16]:
r1 = Rational(4,5)

In [17]:
r1

In [30]:
pi.evalf(n=100)

In [22]:
x = Symbol('x')

In [28]:
expand((x+1)*(x**2+2)*(x**3+5))

In [29]:
factor(6*x**2+5*x+1)

In [33]:
factor(x**2+2*x+1)

In [34]:
factor(121*x**2+33*x+11)

In [35]:
factor((x+2)**2-9)

In [36]:
I**2

In [37]:
I

In [39]:
expand((2+I)**2)

In [40]:
solve(x**2-1,x)

In [42]:
y = Symbol('y')

In [43]:
solve([3*x+5*y-2,2*x+3*y],[x,y])

In [44]:
import matplotlib.pyplot as plt

In [46]:
from scipy import *

In [47]:
3//2

In [49]:
9**(1/2)

In [50]:
from fractions import Fraction

In [51]:
Fraction(3,2)

Fraction(3, 2)